repos:
  # --- Fix YAML files ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: pretty-format-yaml
        args: [--autofix, --indent=2, --preserve-quotes]

  # --- Python formatting ---
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  # --- Python linting ---
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # --- Jupyter Notebook outputs ---
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
