name: SageMaker Pipeline CD

on:
  push:
    branches: [main, uat, production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1   # update region if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Python kernel
      run: |
        pip install ipykernel
        python -m ipykernel install --user --name=python3

    - name: Run SageMaker pipeline notebook
      run: |
        papermill pipeline/pipeline_definition.ipynb output-main.ipynb

